services:

  postgres:
    container_name: unibus_postgres
    image: postgres   
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - unibus_postgres:/data/postgres
      - "./docker/docker-entrypoint-initdb.d/1-create-database.sh:/docker-entrypoint-initdb.d/1-create-database.sh"
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: unibus_pgadmin
    image: dpage/pgadmin4    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - unibus_pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - "postgres"
    restart: unless-stopped

  mosquitto:
    image: iegomez/mosquitto-go-auth:2.1.0-mosquitto_1.6.14
    volumes:
      - ./docker/mosquitto.conf:/etc/mosquitto/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    depends_on:
      - postgres


 
volumes:
  unibus_postgres:
  unibus_pgadmin: