services:

  postgres:
    container_name: unibus_postgres
    image: postgres   
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - unibus_postgres:/data/postgres
      - "./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    restart: unless-stopped
  
  pgadmin:
    container_name: unibus_pgadmin
    image: dpage/pgadmin4    
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - unibus_pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - "postgres"
    restart: unless-stopped

  web:
    container_name: unibus_web
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
    restart: always
    environment:
      - NODE_ENV=development
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app
      - /app/node_modules
    command: pnpm dev --filter='@unibus/web'
  
  websocket:
    container_name: unibus_websocket
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: dev
      args:
        PACKAGE: '@unibus/websocket'
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - web
    volumes:
      - ..:/app
      - /app/node_modules
    command: pnpm dev --filter='@unibus/websocket'
    
  mosquitto:
    container_name: unibus_mqtt
    build:
      context: ./mosquitto
    env_file:
      - ../.env
    depends_on:
      - postgres
      - web
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/tmp/mosquitto.conf

  proxy:
    image: nginx:latest
    container_name: unibus_proxy 
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-unibus.fbi.com}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/certs/:/etc/nginx/certs/:ro
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - mosquitto
      - web
      - websocket
      - pgadmin

volumes:
  unibus_postgres:
  unibus_pgadmin: