services:

  certbot:
    build:
      context: ./certbot
    container_name: unibus_certbot
    environment:
      DOMAIN_NAME: ${NEXT_PUBLIC_DOMAIN_NAME}
    volumes: 
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
      - ./nginx/certs/${NEXT_PUBLIC_DOMAIN_NAME}/:/etc/certbot/certs/${NEXT_PUBLIC_DOMAIN_NAME}/:rw
      - ./certbot/logs:/var/log:rw
    depends_on:
      - certbot-proxy
    entrypoint: ["certbot"]
    command: ["certonly", "--webroot", "-w", "/var/www/certbot", "--force-renewal", "--email", "email@email.com", "-d", "${NEXT_PUBLIC_DOMAIN_NAME}", "--agree-tos", "--deploy-hook", "/usr/local/bin/deploy-script.sh"]

  certbot-proxy:
    image: nginx:latest
    container_name: unibus_proxy 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certbot/www:/var/www/certbot/:ro


volumes:
  unibus_postgres: