services:

  # Serviços de banco de dados
  database:  
    container_name: unibus_database
    image: postgres   
    restart: unless-stopped
    profiles:
      - development
      - production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./database/data:/var/lib/postgresql/data 
      - ./database/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  dbadmin:
    container_name: unibus_dbadmin
    image: dpage/pgadmin4  
    depends_on:
      - "database"  
    profiles:
      - development
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - ./dbadmin/data/:/var/lib/pgadmin/

  # Serviços de aplicação web
  website-development:
    container_name: unibus_website
    build:
      context: ../
      dockerfile: ./services/website/Dockerfile
      target: development
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - development
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ..:/app

  website-production:
    container_name: unibus_website
    build:
      context: ../
      dockerfile: ./services/website/Dockerfile
      target: production
      args:
        - NEXT_PUBLIC_DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME}
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - production
    restart: unless-stopped   
    env_file:
      - ../.env
    volumes:
      - /app/node_modules

  websocket-development:
    container_name: unibus_websocket
    build:
      context: ../
      dockerfile: ./services/websocket/Dockerfile
      target: development
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - development
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
    volumes:
      - ..:/app

  websocket-production:
    container_name: unibus_websocket
    build:
      context: ../
      dockerfile: ./services/websocket/Dockerfile
      target: production
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
    volumes:
      - /app/node_modules

  # Serviços de mensageria
  broker:
    container_name: unibus_broker
    build:
      context: ./broker
    profiles:
      - development
      - production
    depends_on:
      - database
      - website-${NODE_ENV:-development}
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./broker/mosquitto.conf:/tmp/mosquitto.conf
    ports:
      - 1883:1883
      - 8883:8883

  # Serviços de proxy
  proxy-development:
    image: nginx:latest
    container_name: unibus_proxy 
    profiles:
      - development
    depends_on:
      - broker
      - website-${NODE_ENV:-development}
      - websocket-${NODE_ENV:-development}
      - dbadmin
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME:-unibus.fbi.com}
      - NODE_ENV=development
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates:ro
      - ./proxy/certs/:/etc/nginx/certs/:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

  proxy-production:
    image: nginx:latest
    container_name: unibus_proxy 
    profiles:
      - production
    depends_on:
      - broker
      - website-${NODE_ENV:-development}
      - websocket-${NODE_ENV:-development}
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME:-unibus.fbi.com}
      - NODE_ENV=production
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates:ro
      - ./proxy/certs/:/etc/nginx/certs/:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

  # Serviços de certificação
  ssl-webservice:
    image: nginx:latest
    profiles:
      - certbot
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/data/proxy/:/var/www/certbot/:ro
    networks:
      - ssl_network

  ssl:
    image: certbot/certbot:latest
    container_name: unibus_ssl
    profiles:
      - certbot
    depends_on:
      - ssl-webservice
    environment:
      DOMAIN_NAME: ${NEXT_PUBLIC_DOMAIN_NAME}
    volumes: 
      - ./ssl/data/letsencrypt/:/etc/letsencrypt/:rw
      - ./ssl/data/proxy/:/var/www/certbot/:rw
      - ./ssl/data/logs/letsencrypt/:/var/log/letsencrypt/
    networks:
      - ssl_network
    entrypoint: ["certbot"]
    command: "certonly --webroot --webroot-path /var/www/certbot/ --email email@email.com -d ${NEXT_PUBLIC_DOMAIN_NAME} -d websocket.${NEXT_PUBLIC_DOMAIN_NAME} -d broker.${NEXT_PUBLIC_DOMAIN_NAME} -d websocket.broker.${NEXT_PUBLIC_DOMAIN_NAME} --agree-tos"

  gprs_builder:
      container_name: gprs_builder
      build:
        context: ./a9g/
        target: build
        args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
      profiles:
        - a9g
      environment:
        - DISPLAY=${DISPLAY:-':0'}
        - XAUTHORITY=/home/a9g/.Xauthority
        - QT_X11_NO_MITSHM=1
      volumes:
        - ./a9g/data/hex/:/home/a9g/GPRS_C_SDK/hex/
        - ./a9g/data/include/:/home/a9g/include/
        - ./a9g/unibus:/home/a9g/GPRS_C_SDK/unibus/
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ./a9g/data/.Xauthority:/home/a9g/.Xauthority:rw
      devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      stdin_open: true
      tty: true
      entrypoint: /home/a9g/start.sh
      network_mode: none

networks:
  ssl_network:
    driver: bridge
  gprs_network:
    driver: bridge
